/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgeRestrictionUpdateDto
 */
export interface AgeRestrictionUpdateDto {
    /**
     * 
     * @type {number}
     * @memberof AgeRestrictionUpdateDto
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof AgeRestrictionUpdateDto
     */
    restriction: AgeRestrictionUpdateDtoRestrictionEnum;
}


/**
 * @export
 */
export const AgeRestrictionUpdateDtoRestrictionEnum = {
    AllowOnly: 'ALLOW_ONLY',
    Exclude: 'EXCLUDE'
} as const;
export type AgeRestrictionUpdateDtoRestrictionEnum = typeof AgeRestrictionUpdateDtoRestrictionEnum[keyof typeof AgeRestrictionUpdateDtoRestrictionEnum];


/**
 * Check if a given object implements the AgeRestrictionUpdateDto interface.
 */
export function instanceOfAgeRestrictionUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "restriction" in value;

    return isInstance;
}

export function AgeRestrictionUpdateDtoFromJSON(json: any): AgeRestrictionUpdateDto {
    return AgeRestrictionUpdateDtoFromJSONTyped(json, false);
}

export function AgeRestrictionUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRestrictionUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'age': json['age'],
        'restriction': json['restriction'],
    };
}

export function AgeRestrictionUpdateDtoToJSON(value?: AgeRestrictionUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'age': value.age,
        'restriction': value.restriction,
    };
}

