/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgeRestrictionDto
 */
export interface AgeRestrictionDto {
    /**
     * 
     * @type {number}
     * @memberof AgeRestrictionDto
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof AgeRestrictionDto
     */
    restriction: AgeRestrictionDtoRestrictionEnum;
}


/**
 * @export
 */
export const AgeRestrictionDtoRestrictionEnum = {
    AllowOnly: 'ALLOW_ONLY',
    Exclude: 'EXCLUDE'
} as const;
export type AgeRestrictionDtoRestrictionEnum = typeof AgeRestrictionDtoRestrictionEnum[keyof typeof AgeRestrictionDtoRestrictionEnum];


/**
 * Check if a given object implements the AgeRestrictionDto interface.
 */
export function instanceOfAgeRestrictionDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "restriction" in value;

    return isInstance;
}

export function AgeRestrictionDtoFromJSON(json: any): AgeRestrictionDto {
    return AgeRestrictionDtoFromJSONTyped(json, false);
}

export function AgeRestrictionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeRestrictionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'age': json['age'],
        'restriction': json['restriction'],
    };
}

export function AgeRestrictionDtoToJSON(value?: AgeRestrictionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'age': value.age,
        'restriction': value.restriction,
    };
}

