/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlternateTitleUpdateDto
 */
export interface AlternateTitleUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof AlternateTitleUpdateDto
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof AlternateTitleUpdateDto
     */
    title: string;
}

/**
 * Check if a given object implements the AlternateTitleUpdateDto interface.
 */
export function instanceOfAlternateTitleUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function AlternateTitleUpdateDtoFromJSON(json: any): AlternateTitleUpdateDto {
    return AlternateTitleUpdateDtoFromJSONTyped(json, false);
}

export function AlternateTitleUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternateTitleUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'title': json['title'],
    };
}

export function AlternateTitleUpdateDtoToJSON(value?: AlternateTitleUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'title': value.title,
    };
}

