/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorDto
 */
export interface AuthorDto {
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    role: string;
}

/**
 * Check if a given object implements the AuthorDto interface.
 */
export function instanceOfAuthorDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function AuthorDtoFromJSON(json: any): AuthorDto {
    return AuthorDtoFromJSONTyped(json, false);
}

export function AuthorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
    };
}

export function AuthorDtoToJSON(value?: AuthorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'role': value.role,
    };
}

