/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionDto
 */
export interface CollectionDto {
    /**
     * 
     * @type {string}
     * @memberof CollectionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDto
     */
    ordered: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionDto
     */
    seriesIds: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CollectionDto
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CollectionDto
     */
    lastModifiedDate: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionDto
     */
    filtered: boolean;
}

/**
 * Check if a given object implements the CollectionDto interface.
 */
export function instanceOfCollectionDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ordered" in value;
    isInstance = isInstance && "seriesIds" in value;
    isInstance = isInstance && "createdDate" in value;
    isInstance = isInstance && "lastModifiedDate" in value;
    isInstance = isInstance && "filtered" in value;

    return isInstance;
}

export function CollectionDtoFromJSON(json: any): CollectionDto {
    return CollectionDtoFromJSONTyped(json, false);
}

export function CollectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'ordered': json['ordered'],
        'seriesIds': json['seriesIds'],
        'createdDate': (new Date(json['createdDate'])),
        'lastModifiedDate': (new Date(json['lastModifiedDate'])),
        'filtered': json['filtered'],
    };
}

export function CollectionDtoToJSON(value?: CollectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'ordered': value.ordered,
        'seriesIds': value.seriesIds,
        'createdDate': (value.createdDate.toISOString()),
        'lastModifiedDate': (value.lastModifiedDate.toISOString()),
        'filtered': value.filtered,
    };
}

