/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionCreationDto
 */
export interface CollectionCreationDto {
    /**
     * 
     * @type {string}
     * @memberof CollectionCreationDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionCreationDto
     */
    ordered: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionCreationDto
     */
    seriesIds: Array<string>;
}

/**
 * Check if a given object implements the CollectionCreationDto interface.
 */
export function instanceOfCollectionCreationDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ordered" in value;
    isInstance = isInstance && "seriesIds" in value;

    return isInstance;
}

export function CollectionCreationDtoFromJSON(json: any): CollectionCreationDto {
    return CollectionCreationDtoFromJSONTyped(json, false);
}

export function CollectionCreationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionCreationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ordered': json['ordered'],
        'seriesIds': json['seriesIds'],
    };
}

export function CollectionCreationDtoToJSON(value?: CollectionCreationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'ordered': value.ordered,
        'seriesIds': value.seriesIds,
    };
}

