/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PathDto } from './PathDto';
import {
    PathDtoFromJSON,
    PathDtoFromJSONTyped,
    PathDtoToJSON,
} from './PathDto';

/**
 * 
 * @export
 * @interface DirectoryListingDto
 */
export interface DirectoryListingDto {
    /**
     * 
     * @type {string}
     * @memberof DirectoryListingDto
     */
    parent?: string;
    /**
     * 
     * @type {Array<PathDto>}
     * @memberof DirectoryListingDto
     */
    directories: Array<PathDto>;
}

/**
 * Check if a given object implements the DirectoryListingDto interface.
 */
export function instanceOfDirectoryListingDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "directories" in value;

    return isInstance;
}

export function DirectoryListingDtoFromJSON(json: any): DirectoryListingDto {
    return DirectoryListingDtoFromJSONTyped(json, false);
}

export function DirectoryListingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectoryListingDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'directories': ((json['directories'] as Array<any>).map(PathDtoFromJSON)),
    };
}

export function DirectoryListingDtoToJSON(value?: DirectoryListingDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': value.parent,
        'directories': ((value.directories as Array<any>).map(PathDtoToJSON)),
    };
}

