/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupCountDto
 */
export interface GroupCountDto {
    /**
     * 
     * @type {string}
     * @memberof GroupCountDto
     */
    group: string;
    /**
     * 
     * @type {number}
     * @memberof GroupCountDto
     */
    count: number;
}

/**
 * Check if a given object implements the GroupCountDto interface.
 */
export function instanceOfGroupCountDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "group" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function GroupCountDtoFromJSON(json: any): GroupCountDto {
    return GroupCountDtoFromJSONTyped(json, false);
}

export function GroupCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupCountDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': json['group'],
        'count': json['count'],
    };
}

export function GroupCountDtoToJSON(value?: GroupCountDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': value.group,
        'count': value.count,
    };
}

