/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KomgaExtensionDto
 */
export interface KomgaExtensionDto {
    /**
     * 
     * @type {boolean}
     * @memberof KomgaExtensionDto
     */
    read: boolean;
}

/**
 * Check if a given object implements the KomgaExtensionDto interface.
 */
export function instanceOfKomgaExtensionDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "read" in value;

    return isInstance;
}

export function KomgaExtensionDtoFromJSON(json: any): KomgaExtensionDto {
    return KomgaExtensionDtoFromJSONTyped(json, false);
}

export function KomgaExtensionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KomgaExtensionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'read': json['read'],
    };
}

export function KomgaExtensionDtoToJSON(value?: KomgaExtensionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read': value.read,
    };
}

