/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    subtype?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MediaType
     */
    parameters?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof MediaType
     */
    qualityValue?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    wildcardType?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    wildcardSubtype?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    subtypeSuffix?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    charset?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    concrete?: boolean;
}

/**
 * Check if a given object implements the MediaType interface.
 */
export function instanceOfMediaType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaTypeFromJSON(json: any): MediaType {
    return MediaTypeFromJSONTyped(json, false);
}

export function MediaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'subtype': !exists(json, 'subtype') ? undefined : json['subtype'],
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
        'qualityValue': !exists(json, 'qualityValue') ? undefined : json['qualityValue'],
        'wildcardType': !exists(json, 'wildcardType') ? undefined : json['wildcardType'],
        'wildcardSubtype': !exists(json, 'wildcardSubtype') ? undefined : json['wildcardSubtype'],
        'subtypeSuffix': !exists(json, 'subtypeSuffix') ? undefined : json['subtypeSuffix'],
        'charset': !exists(json, 'charset') ? undefined : json['charset'],
        'concrete': !exists(json, 'concrete') ? undefined : json['concrete'],
    };
}

export function MediaTypeToJSON(value?: MediaType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'subtype': value.subtype,
        'parameters': value.parameters,
        'qualityValue': value.qualityValue,
        'wildcardType': value.wildcardType,
        'wildcardSubtype': value.wildcardSubtype,
        'subtypeSuffix': value.subtypeSuffix,
        'charset': value.charset,
        'concrete': value.concrete,
    };
}

