/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuth2ClientDto
 */
export interface OAuth2ClientDto {
    /**
     * 
     * @type {string}
     * @memberof OAuth2ClientDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2ClientDto
     */
    registrationId: string;
}

/**
 * Check if a given object implements the OAuth2ClientDto interface.
 */
export function instanceOfOAuth2ClientDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "registrationId" in value;

    return isInstance;
}

export function OAuth2ClientDtoFromJSON(json: any): OAuth2ClientDto {
    return OAuth2ClientDtoFromJSONTyped(json, false);
}

export function OAuth2ClientDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2ClientDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'registrationId': json['registrationId'],
    };
}

export function OAuth2ClientDtoToJSON(value?: OAuth2ClientDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'registrationId': value.registrationId,
    };
}

