/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageHashKnownDto } from './PageHashKnownDto';
import {
    PageHashKnownDtoFromJSON,
    PageHashKnownDtoFromJSONTyped,
    PageHashKnownDtoToJSON,
} from './PageHashKnownDto';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PagePageHashKnownDto
 */
export interface PagePageHashKnownDto {
    /**
     * 
     * @type {number}
     * @memberof PagePageHashKnownDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePageHashKnownDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePageHashKnownDto
     */
    size?: number;
    /**
     * 
     * @type {Array<PageHashKnownDto>}
     * @memberof PagePageHashKnownDto
     */
    content?: Array<PageHashKnownDto>;
    /**
     * 
     * @type {number}
     * @memberof PagePageHashKnownDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PagePageHashKnownDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PagePageHashKnownDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PagePageHashKnownDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PagePageHashKnownDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagePageHashKnownDto
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagePageHashKnownDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PagePageHashKnownDto interface.
 */
export function instanceOfPagePageHashKnownDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagePageHashKnownDtoFromJSON(json: any): PagePageHashKnownDto {
    return PagePageHashKnownDtoFromJSONTyped(json, false);
}

export function PagePageHashKnownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePageHashKnownDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(PageHashKnownDtoFromJSON)),
        'number': !exists(json, 'number') ? undefined : json['number'],
        'sort': !exists(json, 'sort') ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': !exists(json, 'numberOfElements') ? undefined : json['numberOfElements'],
        'pageable': !exists(json, 'pageable') ? undefined : PageableObjectFromJSON(json['pageable']),
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function PagePageHashKnownDtoToJSON(value?: PagePageHashKnownDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'size': value.size,
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(PageHashKnownDtoToJSON)),
        'number': value.number,
        'sort': SortObjectToJSON(value.sort),
        'numberOfElements': value.numberOfElements,
        'pageable': PageableObjectToJSON(value.pageable),
        'first': value.first,
        'last': value.last,
        'empty': value.empty,
    };
}

