/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CollectionDto } from './CollectionDto';
import {
    CollectionDtoFromJSON,
    CollectionDtoFromJSONTyped,
    CollectionDtoToJSON,
} from './CollectionDto';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageCollectionDto
 */
export interface PageCollectionDto {
    /**
     * 
     * @type {number}
     * @memberof PageCollectionDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCollectionDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCollectionDto
     */
    size?: number;
    /**
     * 
     * @type {Array<CollectionDto>}
     * @memberof PageCollectionDto
     */
    content?: Array<CollectionDto>;
    /**
     * 
     * @type {number}
     * @memberof PageCollectionDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageCollectionDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageCollectionDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageCollectionDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageCollectionDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageCollectionDto
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageCollectionDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageCollectionDto interface.
 */
export function instanceOfPageCollectionDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageCollectionDtoFromJSON(json: any): PageCollectionDto {
    return PageCollectionDtoFromJSONTyped(json, false);
}

export function PageCollectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageCollectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(CollectionDtoFromJSON)),
        'number': !exists(json, 'number') ? undefined : json['number'],
        'sort': !exists(json, 'sort') ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': !exists(json, 'numberOfElements') ? undefined : json['numberOfElements'],
        'pageable': !exists(json, 'pageable') ? undefined : PageableObjectFromJSON(json['pageable']),
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function PageCollectionDtoToJSON(value?: PageCollectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'size': value.size,
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(CollectionDtoToJSON)),
        'number': value.number,
        'sort': SortObjectToJSON(value.sort),
        'numberOfElements': value.numberOfElements,
        'pageable': PageableObjectToJSON(value.pageable),
        'first': value.first,
        'last': value.last,
        'empty': value.empty,
    };
}

