/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageHashUnknownDto
 */
export interface PageHashUnknownDto {
    /**
     * 
     * @type {string}
     * @memberof PageHashUnknownDto
     */
    hash: string;
    /**
     * 
     * @type {number}
     * @memberof PageHashUnknownDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageHashUnknownDto
     */
    matchCount: number;
}

/**
 * Check if a given object implements the PageHashUnknownDto interface.
 */
export function instanceOfPageHashUnknownDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;
    isInstance = isInstance && "matchCount" in value;

    return isInstance;
}

export function PageHashUnknownDtoFromJSON(json: any): PageHashUnknownDto {
    return PageHashUnknownDtoFromJSONTyped(json, false);
}

export function PageHashUnknownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageHashUnknownDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'matchCount': json['matchCount'],
    };
}

export function PageHashUnknownDtoToJSON(value?: PageHashUnknownDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'size': value.size,
        'matchCount': value.matchCount,
    };
}

