/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordUpdateDto
 */
export interface PasswordUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdateDto
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordUpdateDto interface.
 */
export function instanceOfPasswordUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function PasswordUpdateDtoFromJSON(json: any): PasswordUpdateDto {
    return PasswordUpdateDtoFromJSONTyped(json, false);
}

export function PasswordUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function PasswordUpdateDtoToJSON(value?: PasswordUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
    };
}

