/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface R2Device
 */
export interface R2Device {
    /**
     * 
     * @type {string}
     * @memberof R2Device
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof R2Device
     */
    name: string;
}

/**
 * Check if a given object implements the R2Device interface.
 */
export function instanceOfR2Device(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function R2DeviceFromJSON(json: any): R2Device {
    return R2DeviceFromJSONTyped(json, false);
}

export function R2DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): R2Device {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function R2DeviceToJSON(value?: R2Device | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

