/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { R2Locator } from './R2Locator';
import {
    R2LocatorFromJSON,
    R2LocatorFromJSONTyped,
    R2LocatorToJSON,
} from './R2Locator';

/**
 * 
 * @export
 * @interface R2Positions
 */
export interface R2Positions {
    /**
     * 
     * @type {number}
     * @memberof R2Positions
     */
    total: number;
    /**
     * 
     * @type {Array<R2Locator>}
     * @memberof R2Positions
     */
    positions: Array<R2Locator>;
}

/**
 * Check if a given object implements the R2Positions interface.
 */
export function instanceOfR2Positions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "positions" in value;

    return isInstance;
}

export function R2PositionsFromJSON(json: any): R2Positions {
    return R2PositionsFromJSONTyped(json, false);
}

export function R2PositionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): R2Positions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'positions': ((json['positions'] as Array<any>).map(R2LocatorFromJSON)),
    };
}

export function R2PositionsToJSON(value?: R2Positions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'positions': ((value.positions as Array<any>).map(R2LocatorToJSON)),
    };
}

