/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadListCreationDto
 */
export interface ReadListCreationDto {
    /**
     * 
     * @type {string}
     * @memberof ReadListCreationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReadListCreationDto
     */
    summary: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReadListCreationDto
     */
    ordered: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadListCreationDto
     */
    bookIds: Array<string>;
}

/**
 * Check if a given object implements the ReadListCreationDto interface.
 */
export function instanceOfReadListCreationDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "summary" in value;
    isInstance = isInstance && "ordered" in value;
    isInstance = isInstance && "bookIds" in value;

    return isInstance;
}

export function ReadListCreationDtoFromJSON(json: any): ReadListCreationDto {
    return ReadListCreationDtoFromJSONTyped(json, false);
}

export function ReadListCreationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadListCreationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'summary': json['summary'],
        'ordered': json['ordered'],
        'bookIds': json['bookIds'],
    };
}

export function ReadListCreationDtoToJSON(value?: ReadListCreationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'summary': value.summary,
        'ordered': value.ordered,
        'bookIds': value.bookIds,
    };
}

