/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadListRequestBookMatchBookDto } from './ReadListRequestBookMatchBookDto';
import {
    ReadListRequestBookMatchBookDtoFromJSON,
    ReadListRequestBookMatchBookDtoFromJSONTyped,
    ReadListRequestBookMatchBookDtoToJSON,
} from './ReadListRequestBookMatchBookDto';
import type { ReadListRequestBookMatchSeriesDto } from './ReadListRequestBookMatchSeriesDto';
import {
    ReadListRequestBookMatchSeriesDtoFromJSON,
    ReadListRequestBookMatchSeriesDtoFromJSONTyped,
    ReadListRequestBookMatchSeriesDtoToJSON,
} from './ReadListRequestBookMatchSeriesDto';

/**
 * 
 * @export
 * @interface ReadListRequestBookMatchDto
 */
export interface ReadListRequestBookMatchDto {
    /**
     * 
     * @type {ReadListRequestBookMatchSeriesDto}
     * @memberof ReadListRequestBookMatchDto
     */
    series: ReadListRequestBookMatchSeriesDto;
    /**
     * 
     * @type {Array<ReadListRequestBookMatchBookDto>}
     * @memberof ReadListRequestBookMatchDto
     */
    books: Array<ReadListRequestBookMatchBookDto>;
}

/**
 * Check if a given object implements the ReadListRequestBookMatchDto interface.
 */
export function instanceOfReadListRequestBookMatchDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "series" in value;
    isInstance = isInstance && "books" in value;

    return isInstance;
}

export function ReadListRequestBookMatchDtoFromJSON(json: any): ReadListRequestBookMatchDto {
    return ReadListRequestBookMatchDtoFromJSONTyped(json, false);
}

export function ReadListRequestBookMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadListRequestBookMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'series': ReadListRequestBookMatchSeriesDtoFromJSON(json['series']),
        'books': ((json['books'] as Array<any>).map(ReadListRequestBookMatchBookDtoFromJSON)),
    };
}

export function ReadListRequestBookMatchDtoToJSON(value?: ReadListRequestBookMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'series': ReadListRequestBookMatchSeriesDtoToJSON(value.series),
        'books': ((value.books as Array<any>).map(ReadListRequestBookMatchBookDtoToJSON)),
    };
}

