/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadListMatchDto
 */
export interface ReadListMatchDto {
    /**
     * 
     * @type {string}
     * @memberof ReadListMatchDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReadListMatchDto
     */
    errorCode: string;
}

/**
 * Check if a given object implements the ReadListMatchDto interface.
 */
export function instanceOfReadListMatchDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "errorCode" in value;

    return isInstance;
}

export function ReadListMatchDtoFromJSON(json: any): ReadListMatchDto {
    return ReadListMatchDtoFromJSONTyped(json, false);
}

export function ReadListMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadListMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'errorCode': json['errorCode'],
    };
}

export function ReadListMatchDtoToJSON(value?: ReadListMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'errorCode': value.errorCode,
    };
}

