/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingMultiSourceInteger
 */
export interface SettingMultiSourceInteger {
    /**
     * 
     * @type {number}
     * @memberof SettingMultiSourceInteger
     */
    configurationSource: number;
    /**
     * 
     * @type {number}
     * @memberof SettingMultiSourceInteger
     */
    databaseSource: number;
    /**
     * 
     * @type {number}
     * @memberof SettingMultiSourceInteger
     */
    effectiveValue: number;
}

/**
 * Check if a given object implements the SettingMultiSourceInteger interface.
 */
export function instanceOfSettingMultiSourceInteger(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "configurationSource" in value;
    isInstance = isInstance && "databaseSource" in value;
    isInstance = isInstance && "effectiveValue" in value;

    return isInstance;
}

export function SettingMultiSourceIntegerFromJSON(json: any): SettingMultiSourceInteger {
    return SettingMultiSourceIntegerFromJSONTyped(json, false);
}

export function SettingMultiSourceIntegerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingMultiSourceInteger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configurationSource': json['configurationSource'],
        'databaseSource': json['databaseSource'],
        'effectiveValue': json['effectiveValue'],
    };
}

export function SettingMultiSourceIntegerToJSON(value?: SettingMultiSourceInteger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configurationSource': value.configurationSource,
        'databaseSource': value.databaseSource,
        'effectiveValue': value.effectiveValue,
    };
}

