/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingMultiSourceString
 */
export interface SettingMultiSourceString {
    /**
     * 
     * @type {string}
     * @memberof SettingMultiSourceString
     */
    configurationSource: string;
    /**
     * 
     * @type {string}
     * @memberof SettingMultiSourceString
     */
    databaseSource: string;
    /**
     * 
     * @type {string}
     * @memberof SettingMultiSourceString
     */
    effectiveValue: string;
}

/**
 * Check if a given object implements the SettingMultiSourceString interface.
 */
export function instanceOfSettingMultiSourceString(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "configurationSource" in value;
    isInstance = isInstance && "databaseSource" in value;
    isInstance = isInstance && "effectiveValue" in value;

    return isInstance;
}

export function SettingMultiSourceStringFromJSON(json: any): SettingMultiSourceString {
    return SettingMultiSourceStringFromJSONTyped(json, false);
}

export function SettingMultiSourceStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingMultiSourceString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configurationSource': json['configurationSource'],
        'databaseSource': json['databaseSource'],
        'effectiveValue': json['effectiveValue'],
    };
}

export function SettingMultiSourceStringToJSON(value?: SettingMultiSourceString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configurationSource': value.configurationSource,
        'databaseSource': value.databaseSource,
        'effectiveValue': value.effectiveValue,
    };
}

