/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharedLibrariesUpdateDto
 */
export interface SharedLibrariesUpdateDto {
    /**
     * 
     * @type {boolean}
     * @memberof SharedLibrariesUpdateDto
     */
    all: boolean;
    /**
     * 
     * @type {Set<string>}
     * @memberof SharedLibrariesUpdateDto
     */
    libraryIds: Set<string>;
}

/**
 * Check if a given object implements the SharedLibrariesUpdateDto interface.
 */
export function instanceOfSharedLibrariesUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "all" in value;
    isInstance = isInstance && "libraryIds" in value;

    return isInstance;
}

export function SharedLibrariesUpdateDtoFromJSON(json: any): SharedLibrariesUpdateDto {
    return SharedLibrariesUpdateDtoFromJSONTyped(json, false);
}

export function SharedLibrariesUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedLibrariesUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'all': json['all'],
        'libraryIds': json['libraryIds'],
    };
}

export function SharedLibrariesUpdateDtoToJSON(value?: SharedLibrariesUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'all': value.all,
        'libraryIds': Array.from(value.libraryIds as Set<any>),
    };
}

