/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TachiyomiReadProgressUpdateV2Dto
 */
export interface TachiyomiReadProgressUpdateV2Dto {
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressUpdateV2Dto
     */
    lastBookNumberSortRead: number;
}

/**
 * Check if a given object implements the TachiyomiReadProgressUpdateV2Dto interface.
 */
export function instanceOfTachiyomiReadProgressUpdateV2Dto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastBookNumberSortRead" in value;

    return isInstance;
}

export function TachiyomiReadProgressUpdateV2DtoFromJSON(json: any): TachiyomiReadProgressUpdateV2Dto {
    return TachiyomiReadProgressUpdateV2DtoFromJSONTyped(json, false);
}

export function TachiyomiReadProgressUpdateV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TachiyomiReadProgressUpdateV2Dto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastBookNumberSortRead': json['lastBookNumberSortRead'],
    };
}

export function TachiyomiReadProgressUpdateV2DtoToJSON(value?: TachiyomiReadProgressUpdateV2Dto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastBookNumberSortRead': value.lastBookNumberSortRead,
    };
}

