/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TachiyomiReadProgressDto
 */
export interface TachiyomiReadProgressDto {
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressDto
     */
    booksCount: number;
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressDto
     */
    booksReadCount: number;
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressDto
     */
    booksUnreadCount: number;
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressDto
     */
    booksInProgressCount: number;
    /**
     * 
     * @type {number}
     * @memberof TachiyomiReadProgressDto
     */
    lastReadContinuousIndex: number;
}

/**
 * Check if a given object implements the TachiyomiReadProgressDto interface.
 */
export function instanceOfTachiyomiReadProgressDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "booksCount" in value;
    isInstance = isInstance && "booksReadCount" in value;
    isInstance = isInstance && "booksUnreadCount" in value;
    isInstance = isInstance && "booksInProgressCount" in value;
    isInstance = isInstance && "lastReadContinuousIndex" in value;

    return isInstance;
}

export function TachiyomiReadProgressDtoFromJSON(json: any): TachiyomiReadProgressDto {
    return TachiyomiReadProgressDtoFromJSONTyped(json, false);
}

export function TachiyomiReadProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TachiyomiReadProgressDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'booksCount': json['booksCount'],
        'booksReadCount': json['booksReadCount'],
        'booksUnreadCount': json['booksUnreadCount'],
        'booksInProgressCount': json['booksInProgressCount'],
        'lastReadContinuousIndex': json['lastReadContinuousIndex'],
    };
}

export function TachiyomiReadProgressDtoToJSON(value?: TachiyomiReadProgressDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'booksCount': value.booksCount,
        'booksReadCount': value.booksReadCount,
        'booksUnreadCount': value.booksUnreadCount,
        'booksInProgressCount': value.booksInProgressCount,
        'lastReadContinuousIndex': value.lastReadContinuousIndex,
    };
}

