/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebLinkUpdateDto
 */
export interface WebLinkUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof WebLinkUpdateDto
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof WebLinkUpdateDto
     */
    url?: string;
}

/**
 * Check if a given object implements the WebLinkUpdateDto interface.
 */
export function instanceOfWebLinkUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function WebLinkUpdateDtoFromJSON(json: any): WebLinkUpdateDto {
    return WebLinkUpdateDtoFromJSONTyped(json, false);
}

export function WebLinkUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebLinkUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function WebLinkUpdateDtoToJSON(value?: WebLinkUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'url': value.url,
    };
}

