/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebLinkDto
 */
export interface WebLinkDto {
    /**
     * 
     * @type {string}
     * @memberof WebLinkDto
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof WebLinkDto
     */
    url: string;
}

/**
 * Check if a given object implements the WebLinkDto interface.
 */
export function instanceOfWebLinkDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function WebLinkDtoFromJSON(json: any): WebLinkDto {
    return WebLinkDtoFromJSONTyped(json, false);
}

export function WebLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebLinkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'url': json['url'],
    };
}

export function WebLinkDtoToJSON(value?: WebLinkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'url': value.url,
    };
}

