/* tslint:disable */
/* eslint-disable */
/**
 * Komga API
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WPLinkDto
 */
export interface WPLinkDto {
    /**
     * 
     * @type {string}
     * @memberof WPLinkDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof WPLinkDto
     */
    rel?: string;
    /**
     * 
     * @type {string}
     * @memberof WPLinkDto
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof WPLinkDto
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WPLinkDto
     */
    templated?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WPLinkDto
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof WPLinkDto
     */
    height?: number;
}

/**
 * Check if a given object implements the WPLinkDto interface.
 */
export function instanceOfWPLinkDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WPLinkDtoFromJSON(json: any): WPLinkDto {
    return WPLinkDtoFromJSONTyped(json, false);
}

export function WPLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WPLinkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'rel': !exists(json, 'rel') ? undefined : json['rel'],
        'href': !exists(json, 'href') ? undefined : json['href'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'templated': !exists(json, 'templated') ? undefined : json['templated'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function WPLinkDtoToJSON(value?: WPLinkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'rel': value.rel,
        'href': value.href,
        'type': value.type,
        'templated': value.templated,
        'width': value.width,
        'height': value.height,
    };
}

